# Generated by Django 4.1.4 on 2022-12-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_postpage_intro_postpagetags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='intro',
        ),
    ]
