# Generated by Django 4.1.4 on 2022-12-28 21:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='body',
            field=wagtail.fields.StreamField([('h1', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image_carousel', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock())), ('bullet_list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock())), ('image_text', wagtail.blocks.StructBlock([('image1', wagtail.images.blocks.ImageChooserBlock()), ('caption1', wagtail.blocks.CharBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('caption2', wagtail.blocks.CharBlock())])), ('quote', wagtail.blocks.StructBlock([('quote_by', wagtail.blocks.CharBlock()), ('quotes', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=None),
        ),
    ]
